### ISSUE TITLE
Incompatible with DocPad v6.80 and above 

### ISSUE THREAD

**Issue by cattermo** [docpad/docpad-plugin-assets#5]
Plugin requires updating to CoffeeScript v2. This can be done automatically via running https://github.com/bevry/boundation on it. 
If you would like the DocPad team to do it, then transfer the repo to the https://github.com/docpad organisation, and run the following:

npm owner add balupton docpad-plugin-assets
npm owner add bevryme docpad-plugin-assets

**Comment by mcdee** [comment]
I'm happy to hand this over but I cannot transfer the repo to the organisation as it says I do not have permissions to create repositories for the docpad organisation.

**Comment by balupton** [comment]
Just added @mcdee to the docpad extras team, once you accept you should be able to transfer

**Comment by mcdee** [comment]
Should be transferred and npm access granted as above.

**Comment by balupton** [comment]
Great, I’ll get to the upgrade tomorrow.

**Comment by balupton** [comment]
I've applied the necessary updates, however the tests seem sporadic. Not sure what is going on.

**Comment by balupton** [comment]
Okay, I have a suspicion. Leave it with me for now. Upgrading all the remaining plugins should be done by the week’s end.

**Comment by balupton** [comment]
> Any updates on this?

https://discuss.bevry.me/t/remaining-outdated-plugins/255?u=balupton

**Comment by balupton** [comment]
should now work
